spring:
  application:
    name: supplement-stock-manager
  datasource:
    url: jdbc:mysql://localhost:3306/supplement_stock_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update